### ISSUE TITLE
Main view should be called widget.xml and not waterfall.xml

### ISSUE THREAD

**Issue by torlanco** [m1ga/com.miga.waterfall#1]
I get this error, that should be corrected when the widget.xml view is found.

```
[ERROR] :  widget "com.miga.waterfall" view "widget" does not exist.
[ERROR] :  The following paths were inspected:
[ERROR] :  /Users/torlanco/Documents/Appcelerator_Studio_Workspace/museo-tabs/app/widgets/com.miga.waterfall/views/android/widget
[ERROR] :  /Users/torlanco/Documents/Appcelerator_Studio_Workspace/museo-tabs/app/widgets/com.miga.waterfall/views/widget
[ERROR] :  /Users/torlanco/.appcelerator/install/4.1.0/package/node_modules/appc-cli-titanium/node_modules/alloy/widgets/com.miga.waterfall/views/android/widget
[ERROR] :  /Users/torlanco/.appcelerator/install/4.1.0/package/node_modules/appc-cli-titanium/node_modules/alloy/widgets/com.miga.waterfall/views/widget
[ERROR] :  Alloy compiler failed
TRACE  | titanium exited with exit code 1
ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/torlanco/.appcelerator/install/4.1.0/package/node_modules/appc-cli-titanium/plugins/run.js:84:66)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
[ERROR] Application Installer abnormal process termination. Process exit value was 1
```

**Comment by m1ga** [comment]
how did you include the widget? Folder and XML file?

The widget should be in "appname/teilen/app/widgets/com.miga.waterfall/"
appname/config.json should include
        "com.miga.waterfall": "1.0"
in the dependencies section.

and then you can use <Widget id="waterfall" src="com.miga.waterfall"/> inside your view
